### PR TITLE
Update router.py

### PR DESCRIPTION
**Pull request by Crossedrogue123**
Get_config was undefined when I tried to run it. This fix worked.

### CODE REVIEW

**Comment by yukiarimo** [comment]
Tf. I’ll check it tomorrow

**Comment by Crossedrogue123** [comment]
Sorry I had mad a mistake with my issue. There was nothing wrong with your code.


________________________________

**Comment by Crossedrogue123** [comment]
Dear Mr.Arimo,

It was an error on my part, I attempted to use visual studio to launch the script so it said that
self.config was not defined, so I thought it was an issue with the script. I wanted to try and help you fix it so I made a pull request, but it turned out to just be an error with the way I was trying to launch the script. Running it in command prompt I had no issues. I actually support this project of yours, it is nice to have a bot that is not censored. I would support your project financially, however at the moment I am short on funds. I truly think this has a lot of potential. I will also let you know if I come into any great ideas to improve or make the program more unique, separating it more from your typical relationship bot like replica.

kind regards,
Robert Bohn


________________________________

**Comment by yukiarimo** [comment]
Thanks, I'm glad to hear that you got the error! 💪

If you want to discuss our secret stuff and ideas for the future, please DM me on Discord: `yukiarimo#4577`, and I can add you to our server if you want :)

**Pull request closed without merging**
